

all: src/main.cc src/solver.cc src/bruteforce.cc src/grasp.cc src/brkga.cc
	g++ -o main src/main.cc src/solver.cc src/bruteforce.cc src/grasp.cc src/brkga.cc -O3 -std=c++11 -Iinclude -Wall -fopenmp
